[phases.setup]
nixPkgs = ["nodejs", "chromium", "glibc", "nss", "atk", "at-spi2-atk", "libdrm", "mesa", "libxkbcommon", "pango", "cairo"]

[phases.build]
cmds = ["npm install", "npx puppeteer browsers install chrome"]
