[phases.setup]
nixPkgs = ["...", "nodejs", "chromium", "glib", "nss", "atk", "at-spi2-atk", "libdrm", "mesa", "libxkbcommon", "pango", "cairo", "alsa-lib"]

[phases.build]
cmds = ["npm install", "npx puppeteer browsers install chrome"]
